schemaVersion: 1
name: my-project
root: .
sourceRoots:
    - src
resourceRoots:
    - src/main/resources
webappDir: WebRoot
outputDir: build/classes
buildFile: build.xml
buildTargets:
    - compile
sourceLevel: "1.6"
targetLevel: "1.6"
encoding: gbk
buildTool: ant
contextPath: /
